//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod bir araÃ§ tarafÄ±ndan oluÅŸturuldu.
//     Ã‡alÄ±ÅŸma ZamanÄ± SÃ¼rÃ¼mÃ¼: 4.0.30319.42000
//
//     Bu dosyada yapÄ±lan deÄŸiÅŸiklikler yanlÄ±ÅŸ davranÄ±ÅŸa yol aÃ§abilir ve ÅŸu durumda kaybolur
//     kod yeniden oluÅŸturulduÄŸunda.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Properties
{


    /// <summary>
    ///   YerelleÅŸtirilmiÅŸ dizeleri vs. aramak iÃ§in tÃ¼rÃ¼ kesin belirlenmiÅŸ bir kaynak sÄ±nÄ±fÄ±.
    /// </summary>
    // Bu sÄ±nÄ±f, StronglyTypedResourceBuilder tarafÄ±ndan otomatik olarak
    // ResGen ya da Visual Studio gibi bir araÃ§ ile oluÅŸturuldu.
    // Bir Ã¼ye eklemek ya da kaldÄ±rmak iÃ§in .ResX dosyanÄ±zÄ± dÃ¼yenleyin, sonra da ResGen
    // Ã¶ÄŸesini /str seÃ§eneÄŸiyle yeniden Ã§alÄ±ÅŸtÄ±rÄ±n veya VS projenizi yeniden derleyin.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Bu sÄ±nÄ±f tarafÄ±ndan kullanÄ±lan, Ã¶nbelleÄŸe alÄ±nmÄ±ÅŸ ResourceManager Ã¶rneÄŸini dÃ¶ndÃ¼rÃ¼r.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((resourceMan == null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Server.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   GeÃ§erli iÅŸ parÃ§acÄ±ÄŸÄ±nÄ±n CurrentUICulture Ã¶zelliÄŸini, tÃ¼rÃ¼ kesin belirlenmiÅŸ
        ///   bu kaynak sÄ±nÄ±fÄ±nÄ± kullanan tÃ¼m kaynak aramalarÄ± iÃ§in geÃ§ersiz kÄ±lar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
    }
}
